apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-verify-script
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/*").AsConfig | nindent 2 }}
